### ISSUE TITLE
Some txt missing

### ISSUE THREAD

**Issue by lyuweiwang** [canonical-capsules/canonical-capsules#1]
Hello, I find that some txt files are needed in data_dump_folder. However, the folder is not included in this project. Could you please upload these txt files such as synsetoffset2category.txt and train_cat.txt? Besides, would you please instruct how to train with custom data?

**Comment by weiweisun2018** [comment]
Hi, `synsetoffset2category.txt` is downloaded along with ShapeNet Dataset. You don't need it if you convert the downloaded dataset into h5 files as we did.  `train_cat.txt` is a list of h5 filenames of categories. You could have it by simply running `ls train_h5_data_folder train_cat.txt > train_cat.txt`. About custom data, probably you want to have a look at our data_loader. Or you could simply make your own loader because the only input for the training is the point clouds. Let me know if you have further questions.

**Comment by toobaimt** [comment]
Hi,
Can you also kindly comment on the contents of "random_T_100k_uni-180-0.2.h5" for 2D plane testing in ShapeNetLoader.py, Line # 23?

**Comment by wsunid** [comment]
Hi, ```random_T_100k_uni-180-0.2.h5``` is a set of pre-generated rigid random transformation matrixes, which aims to fix the random pose in testing. Hope it could help.

**Comment by toobaimt** [comment]
So we can randomly generate a set of rigid transformations and use that? Because the h5 file is not provided.
Thanks in advance!

**Comment by wsunid** [comment]
Yeah, you can generate the random pose yourself. The reason behind this h5 file is that I want to fix the random pose when comparing it with other methods in the registration task. 

But I think in the 2D toy example, it will be more interesting to the result in the visualization mode (by rotating object and observe the result of the decomposition, reconstruction). It basically shows that the network handles the shape in all possible poses.

**Comment by toobaimt** [comment]
Great, thank you!
